[versions]
kotlin = "2.0.0"
android-gradle = "8.5.0"
central-portal-plus = "1.2.5"
central-portal-plus-last = "1.2.4"
[libraries]
commons-io = { module = "commons-io:commons-io", version = "2.16.1" }
gson = { module = "com.google.code.gson:gson", version = "2.11.0" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "4.12.0" }
zip4j = { module = "net.lingala.zip4j:zip4j", version = "2.11.5" }
stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradle-publish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
central-portal-plus = { id = "cn.lalaki.central", version.ref = "central-portal-plus" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.6" }